### ISSUE TITLE
PYBIND11_MODULE MSVC 2017 python 3.6 issue: Python Version mismatch

### ISSUE THREAD

**Issue by Mjang714** [Microsoft/python-sample-vs-cpp-extension#2]
Hey,
I was following the microsoft visual studio guide on how to setup a python wrapper for c++ via pybind11 here: https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2017 . However after following the instructions my PYBIND11_MODULE within MSVC 2017 seems to think that there is a python version mismatch. Also when I try to build I run into numerous error such as:

-  E0020	identifier "ULONG" is undefined	superfastcode2	1006

When I deprecated the project to use python 2.7 everything worked as expected. I was curious if anyone knew any solution to this since I would like to use python 3.6 or greater. I am relatively new to developing on Windows so sorry if my question seems a little basic. Thanks!!!!

**Comment by kraigb** [comment]
Thanks for the report. I'll look into it when I have a chance (but that might be a little while given a relatively short time I have before the holidays).

**Comment by Mjang714** [comment]
Thanks. I wanted to give you a quick update. I tried building the package with the python setup script in your example, and ran the script to create the python module and it worked fine with python 3.7. I am beginning to think that this specific issue with the way visual studio is set up on my PC.  I am using the community edition is there any additional setup that I may be missing?

**Comment by kraigb** [comment]
I'm not sure...I've been using the Community edition as well. Offhand, I'm thinking that it's perhaps a mismatch of the selected interpreter for the project in VS. 

You said you built successfully on the command line, yes? If you just run "python --version", that reports 3.7, correct? And what's the output from "where python.exe"? (To see which installation you're running.)

In VS, then, in Solution Explorer, expand the "CppAndPython" project, then expand "Python Environments". What environment is shown there? If it doesn't match the Python 3.7 that you successfully built with, right-click Python Environments, select "Add/Remove Python Environments", and set the box for the same 3.7 interpreter. Then try the build again. (The Python Environments *window*, which is a peer to Solution Explorer, is where you can look at the details of each of the interpreters.)

**Comment by Mjang714** [comment]
when running "python --version" I did indeed get Python 3.7.1. When running the python command from the terminal I get 
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.


 I did however figure out what the issue was though. The Preprocessor Py_LIMITED_API; prevented the macro for Py_Buffer from being defined, and also prevented python version retrieval I guess. I am not sure why this would be a problem from 2.7.11 to 3.X. I think the authors of Python 3.X choose to deprecate some of the functionalities of Py_LIMITED_API for some reason, again I am not certain why. Have anyone else ever run into an issue with Py_LIMITED_API being defined in the Preprocessors? Thanks again for all your help!!! HAPPY HOLIDAYS!!!!

**Comment by kraigb** [comment]
Having (finally) reviewed this all, I see that Py_LIMITED_API shouldn't be included when using PyBind11. This is correct in the sample: the superfastcode2 project, which is oriented around PyBind11, doesn't include that preprocessor definition (the superfastcode project using CPython, does).

Clearly, then, the only fix needed here is to clarify the documentation to use Py_LIMITED_API with only CPython.

Thanks for pointing it out!

**Comment by Mjang714** [comment]
Thanks!!!!
